---
kind: pipeline
name: better-ajv-errors
steps:
  - name: build
    image: node:20-alpine3.19
    commands:
      - yarn
      - yarn build
  - name: test
    image: node:20-alpine3.19
    commands:
      - yarn test-ci
    depends_on:
      - build
  - name: publish
    image: node:20-alpine3.19
    commands:
      - echo -n $NPMRC | base64 -d > /root/.npmrc
      - npm publish
      - rm /root/.npmrc
    depends_on:
      - test
    environment:
      NPMRC:
        from_secret: NPMRC_GAR_CI
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

---
kind: signature
hmac: 26678eb7c75993fb2454bdeaa577268e96a3ffc423fbeafdfd3d99de4cbc0254
