---
kind: pipeline
name: better-ajv-errors
steps:
  - name: build
    image: node:20-alpine3.19
    commands:
      - yarn
      - yarn build
  - name: test
    image: node:20-alpine3.19
    commands:
      - yarn test-ci
    depends_on:
      - build
  - name: publish
    image: node:20-alpine3.19
    commands:
      - echo -n $NPMRC | base64 -d > /root/.npmrc
      - npm publish --dry-run
      - rm /root/.npmrc
    depends_on:
      - test
    environment:
      NPMRC:
        from_secret: NPMRC_GAR_CI
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

---
kind: signature
hmac: 8dbeb98185255b38f0bd74d22b0a7fc18767697813e4f67bf0d5875e8cabc761
